### ISSUE TITLE
Some words in freq dictionary have a value of -1

### ISSUE THREAD

**Issue by is4ac** [is4ac/ohno-wordflood#1]

**Comment by mberland** [comment]
could you give an example? i don't see any... in fact, i think you might be wrong (at least in `sortedenddict.csv`).

**Comment by mberland** [comment]
i might have messed up my C# rather than my data... i'd say that was _likely_, if anything. i mean, i don't know C# very well, so...

**Comment by is4ac** [comment]
I believe the word HOR ended up having a freq of -1 somehow. I didn't actually look in the text file yet so it must be a bug somewhere else then!

**Comment by is4ac** [comment]
Ah, I think I figured it out. It's because the two dictionaries don't match exactly, so a word that exists in the words dictionary didn't exist in the freq dictionary, causing an invalid value.

**Comment by mberland** [comment]
That makes sense!

**Comment by mberland** [comment]
You should probably use my (scrabble) dictionary for both

**Comment by is4ac** [comment]
Yup, just fixed!
